version: '3.8'

name: virtual_infrastructure

services:
  nginx:
    image: nginx:1.21
    container_name: nginx_server
    ports:
      - "8080:80"  
    volumes:
      - ./html:/usr/share/nginx/html  
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf 
    networks:
      - web_network  
    depends_on:
      - mysql  

  mysql:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: my_database  
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  
    configs:
      - source: init_sql
        target: /docker-entrypoint-initdb.d/init.sql 
    networks:
      - web_network  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  
      PMA_USER: root  
      PMA_PASSWORD: rootpassword  
    ports:
      - "8081:80"  
    networks:
      - web_network  
    depends_on:
      - mysql 

networks:
  web_network:
    driver: bridge 

volumes:
  mysql_data:
    driver: local  

configs:
  nginx_conf:
    file: ./nginx.conf  
  init_sql:
    file: ./sql/init.sql  


